### ISSUE TITLE
GeoJSON to poly -- Inaccurate documentation example. 

### ISSUE THREAD

**Issue by W-Ely** [Rub21/geokit#102]
Here: http://devseed.com/geokit-doc-seed/usage/geojson-to-poly/
The command line example is:
```
docker run --rm -v ${PWD}:/mnt/data developmentseed/geokit:node.latest geokit \
    geojson2poly input.geojson output.poly
```
    
but should be:

```
docker run --rm -v ${PWD}:/mnt/data developmentseed/geokit:node.latest \
    geojson2poly input.geojson output.poly
```

Without the `geokit`

**Comment by piligab** [comment]
@W-Ely thank you so much for this. I have updated the [documentation](http://devseed.com/geokit-doc-seed/usage/geojson-to-poly/).
