### ISSUE TITLE
geojson -> bbox

### ISSUE THREAD

**Issue by Rub21** [Rub21/geokit#12]
Sometimes we need the box of a geojson. 

cc. @piligab @karitotp

**Comment by karitotp** [comment]
@Rub21 what about of this functionality https://github.com/developmentseed/geokit/blob/master/src/bbox.js? I think this already is doing that or we need another?

**Comment by karitotp** [comment]
This functionality was missing in the README, I just added it and i did a pull request.

**Comment by Rub21** [comment]
thank you @karitotp!!
