### ISSUE TITLE
Error in creating the image

### ISSUE THREAD

**Issue by GotamDahiya** [Rub21/geokit#88]
[Line 97](https://github.com/developmentseed/geokit/blob/d3ebbaf495a73cb80929cb340b3e3d2acbdd4b8d/Dockerfile#L97
)

get-pip.py no longer exists at the specified [URL](https://bootstrap.pypa.io/2.7/get-pip.py)

Due to this error, the image cannot be built.

**Comment by GotamDahiya** [comment]
Pip for python 2.7 can be found here [Pip 2.7](https://bootstrap.pypa.io/pip/2.7/get-pip.py)

**Comment by yunica** [comment]
Hey @GotamDahiya 
In order to improve our GEOKIT tool, we have built images by technologies, you can try the new installation in http://devseed.com/geokit-doc-seed/installation/installation/.

**Comment by GotamDahiya** [comment]
cool thanks, will try it out.
Should I close this issue?
